### PR TITLE
chore: added welcome directory inside .github 

### LINKED ISSUE #103: No welcome directory inside .github
**Description**
The welcome directory inside .github is not present, the directory should contain images for meshery celebrations, that are used in [config.yml](https://github.com/meshery/meshery-octarine/tree/master/.github)

**Expected Behavior**
There should be  a welcome folder in .github directory that contains svg images for meshery-celebrations.

**Screenshots**

This is the current structure of .github directory.

**Enviroment:**
 - OS: Ubuntu
 - Browser: Brave
 - Version: 22
 - Device: Laptop

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Yana-Gupta**
**Description**

This PR fixes #103

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yana-Gupta** [comment]
@leecalcote Can you review it once.

**Comment by leecalcote** [comment]
@goldfishdolphin @thisiskaransgit

**Comment by leecalcote** [comment]
Sign your commits, please.

**Comment by leecalcote** [comment]
https://github.com/meshery/meshery-octarine/pull/104#issuecomment-1633645018

**Review by goldfishdolphin — APPROVED** [review]
Well done @Yana-Gupta  👏🏽
LGTM

**Pull request merged**
