### PR TITLE
updated OctarineCient with Client in meshery-octarine

### PR DESCRIPTION
**Pull request by ashiscs**

### CODE REVIEW

**Comment by leecalcote** [comment]
This PR is for purposes of implementing fixes for lint issues.

**Comment by girishranganathan** [comment]
@ashiscs thx for this PR.
Can you please get these fixed:
- https://github.com/layer5io/meshery-octarine/pull/26/checks?check_run_id=256191038#step:4:108
- https://github.com/layer5io/meshery-octarine/pull/26/checks?check_run_id=256191057#step:4:97

**Comment by ashiscs** [comment]
Ok sir @girishranganathan

**Comment by leecalcote** [comment]
@ashiscs checking in here in case you have an update.

**Comment by leecalcote** [comment]
Closing in lieu of PR #42.

**Pull request closed without merging**
